### ISSUE TITLE
Not an issue -- is there a .jar file available for this? =)

### ISSUE THREAD

**Issue by reallydrained** [Roadhog360/SimpleSkinBackport#10]
I would love to try this out, not sure how to compile myself so I'm just curious if there's a .jar file somewhere I could download. Thank you for all the amazing work you do, Roadhog360.

**Comment by Roadhog360** [comment]
Look under the "actions" tab

**Comment by reallydrained** [comment]
> Look under the "actions" tab

They say expired =(
![Screenshot 2024-10-31 235742](https://github.com/user-attachments/assets/7bcbb2ca-b084-4116-bbc9-813d7dea37ba)

**Comment by Roadhog360** [comment]
p.s. You can my [Discord server here](https://discord.gg/vFhf7acgMK) and ask questions there (this was linked in EFR's page as well)

**Comment by Roadhog360** [comment]
I generated a newer one and made it expire after 90 days instead of 31

**Comment by reallydrained** [comment]
> I generated a newer one and made it expire after 90 days instead of 31

Thank you so much! I will be sure to join the Discord as well =D
