### ISSUE TITLE
Fix of Hardcore Ender Expansion and Iguanas Tinker Tweaks heads

### ISSUE THREAD

**Issue by Omgise** [Roadhog360/SimpleSkinBackport#2]

**Comment by Roadhog360** [comment]
Please describe the issue, thanks

**Comment by Omgise** [comment]
The skin will overlap the skull

**Comment by Roadhog360** [comment]
![2024-09-02_21 28 20](https://github.com/user-attachments/assets/adb57213-11db-44b5-8a4f-a342358af7df)

You mean this? This is vanilla behavior. But you're right, I should fix it
