### ISSUE TITLE
Hardcore Ender Expansion heads rendering error

### ISSUE THREAD

**Issue by Omgise** [Roadhog360/SimpleSkinBackport#5]
https://github.com/user-attachments/assets/d28b601a-842d-4cfa-a1ce-2cc3fbb61002

**Comment by Roadhog360** [comment]
Lmao, wtf is HEE doing??

**Comment by Roadhog360** [comment]
![2024-09-08_04 40 12](https://github.com/user-attachments/assets/3519fbde-6698-4fa5-bdc6-26765c170d40)
![2024-09-08_04 40 14](https://github.com/user-attachments/assets/c68d2934-a94c-4551-9d86-200e94ac9638)
![2024-09-08_04 40 15](https://github.com/user-attachments/assets/fef94582-8607-4182-8a7f-4a2b626a698a)
Cannot reproduce

**Comment by Omgise** [comment]
This is also a problem caused by AsieLib

**Comment by Roadhog360** [comment]
I've installed AsieLib and still cannot reproduce this issue.

**Comment by Omgise** [comment]
Now I find that backhand is the cause of the problem

**Comment by Roadhog360** [comment]
Still cannot reproduce with backhand installed on a minimal instance

**Comment by Omgise** [comment]
I've gone to work now. I may have to wait for the weekend to sort out the problem

**Comment by Omgise** [comment]
I found that with the latest `SimplesKinbackport-F67FA888-master +f67fa8890c-dirty`, this bug disappeared
![image](https://github.com/user-attachments/assets/825a600d-589c-41c5-aa43-3bfe7a5ea76f)

**Comment by Roadhog360** [comment]
I think we can consider it fixed then! Thanks for testing

**Comment by Roadhog360** [comment]
Btw, I hope my new skin solution has worked good so far in your stuff, my goal was to replace SkinPort and other skin backport alternatives.

**Comment by Omgise** [comment]
Thank you for your hard work, thank you!
